version: '3'

services:
  api-solid-pg:
    image: bit/postgresql
    ports:
      - 5432:5432
    environment:
    - POSTGRESQL_USERNAME=docker
    - POSTGRESQL_PASSWORD=docker
    - POSTGRESQL-DATABASE=apisolid 